# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0007_auto_20170604_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
    ]
