# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0011_auto_20170604_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
