# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0014_auto_20170604_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
        migrations.AddField(
            model_name='userpost',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
