# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microblog', '0015_auto_20170604_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
