# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0021_userpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
    ]
